// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sblgelujmjtwzhdwdnlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibGdlbHVqbWp0d3poZHdkbmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTAwNTAsImV4cCI6MjA2NDg2NjA1MH0.LEOry6Q_GMXq__B3qtmz67Wc3AMbuu498vt3P-hfhVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);